
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

colors = {
    'bg': '#222222',
    'title': '#EEEEEE',
    'panelbg': '#333333',
    'debugred': '#FF0000',
    'debugblue': '#0000FF'
}


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg=colors['bg'])

bgcanvas = Canvas(
    window,
    bg=colors['debugred'],
    height=720,
    width=1280,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

bgcanvas.pack(side="left", fill="both", expand=True)

bgcanvas.create_rectangle(
    10, 10,
    652, 90,
    fill=colors['panelbg'],
    outline="")

bgcanvas.create_text(
    36,
    16,
    anchor="nw",
    text="Práctica de Inteligencia Artificial",
    fill=colors['title'],
    font=("Cascadia Code", -28)
)

bgcanvas.create_text(
    36,
    52,
    anchor="nw",
    text="Metro de Kiev | Grupo 12",
    fill=colors['title'],
    font=("Cascadia Code", -20)
)

bgcanvas.create_rectangle(
    10, 100,
    356, 200,
    fill=colors['panelbg'],
    outline="")

bgcanvas.create_text(
    20,
    110,
    anchor="nw",
    text="Desde",
    fill=colors['title'],
    font=("Cascadia Code", -20)
)

bgcanvas.create_text(
    180,
    110,
    anchor="nw",
    text="Hasta",
    fill=colors['title'],
    font=("Cascadia Code", -20)
)

desdeinput = Entry(
    window,
    bg=colors['debugred']
)

desdeinput.place(x=20, y=160)

hastainput = Entry(
    window,
    bg=colors['debugred']
)

hastainput.place(x=180, y=160)

buscarbutton = Button(
    window,
    text="Buscar",
    bg=colors['debugblue'],
    padx=56,
    pady=14,
)

buscarbutton.place(x=200, y=200)

bgcanvas.create_rectangle(
    200, 200,
    356, 250,
    fill=colors['panelbg'],
    outline="")

bgcanvas.create_rectangle(
    10, 260.0,
    356, 600.0,
    fill=colors['panelbg'],
    outline="")



# canvas = Canvas(
#     window,
#     bg=colors['bg'],
#     height = 920,
#     width = 1440,
#     bd = 0,
#     highlightthickness = 0,
#     relief = "ridge"
# )
#
# canvas.place(x = 0, y = 0)
# canvas.create_rectangle(
#     91.996826171875,
#     94.0,
#     1348.003173828125,
#     94.0,
#     fill="#000000",
#     outline="")
#
# canvas.create_rectangle(
#     92.0,
#     183.0,
#     605.0,
#     374.0,
#     fill="#000000",
#     outline="")
#
# canvas.create_rectangle(
#     153.0,
#     109.6732177734375,
#     1337.81005859375,
#     988.1900024414062,
#     fill="#000000",
#     outline="")
#
# canvas.create_rectangle(
#     0.0,
#     907.0,
#     1440.0,
#     1024.0,
#     fill="#000000",
#     outline="")
#
# canvas.create_text(
#     92.0,
#     33.0,
#     anchor="nw",
#     text="Práctica de Inteligencia Artificial: Perdidos por el metro de Kiev",
#     fill="#FAFAFA",
#     font=("Sen Bold", 40 * -1)
# )



window.resizable(True, True)
window.mainloop()
